### PR TITLE
add API list

### PR DESCRIPTION
**Pull request by wangkirin**
Signed-off-by: Wang Qilin <qilin.wang@huawei.com>

### CODE REVIEW

**Comment by wangkirin** [comment]
hi @genedna , there are two issue need to be confirm:
1. In APIs spec of S3, it provides both `PUT` and `POST` method for user to upload an object and these two share the same function, but in some other object storage like `minio` it only provides `PUT` method, should we add `POST` to keep the same with S3?
2. At the start of Arkor ,we don't consider bucket permission strategy like `ACL` to simplify the operation, but should we add basic bucket policy like readonly/readwrite/writeonly ?

**Comment by genedna** [comment]
@wangkirin 

1. Only support `PUT` just now like `minio`, support `POST` later.
2. Focusing on the basic functions, permission maybe later. And arkor is simple storage service for embedding into other Golang application like git service or software repository, not provide a common storage service replace `minio` or `swift`.

**Comment by genedna** [comment]
@wangkirin 

```
GET [`/:bucketName/:objectName`]
```
Replace:

```
GET [`/:bucket/:object`]
```

Try to use one or more short words as a variable name.

**Comment by wangkirin** [comment]
@genedna  Done

**Comment by genedna** [comment]
@wangkirin 

PUT [`/:bucket/:destinationObject`]

replace with:

PUT [`/:bucket/:destination`]

**Comment by genedna** [comment]
LGTM

**Pull request merged**
